// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_config_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_config_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_config_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_config_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_config_2eproto;
namespace bazel_template {
namespace proto {
class BaseConfig;
struct BaseConfigDefaultTypeInternal;
extern BaseConfigDefaultTypeInternal _BaseConfig_default_instance_;
}  // namespace proto
}  // namespace bazel_template
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace bazel_template {
namespace proto {

// ===================================================================


// -------------------------------------------------------------------

class BaseConfig final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:bazel_template.proto.BaseConfig) */ {
 public:
  inline BaseConfig() : BaseConfig(nullptr) {}
  ~BaseConfig() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BaseConfig(
      ::google::protobuf::internal::ConstantInitialized);

  inline BaseConfig(const BaseConfig& from) : BaseConfig(nullptr, from) {}
  inline BaseConfig(BaseConfig&& from) noexcept
      : BaseConfig(nullptr, std::move(from)) {}
  inline BaseConfig& operator=(const BaseConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline BaseConfig& operator=(BaseConfig&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BaseConfig& default_instance() {
    return *internal_default_instance();
  }
  static inline const BaseConfig* internal_default_instance() {
    return reinterpret_cast<const BaseConfig*>(
        &_BaseConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BaseConfig& a, BaseConfig& b) { a.Swap(&b); }
  inline void Swap(BaseConfig* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BaseConfig* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BaseConfig* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<BaseConfig>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BaseConfig& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BaseConfig& from) { BaseConfig::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(BaseConfig* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "bazel_template.proto.BaseConfig"; }

 protected:
  explicit BaseConfig(::google::protobuf::Arena* arena);
  BaseConfig(::google::protobuf::Arena* arena, const BaseConfig& from);
  BaseConfig(::google::protobuf::Arena* arena, BaseConfig&& from) noexcept
      : BaseConfig(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kServerAddrFieldNumber = 1,
    kGrpcServerPortFieldNumber = 2,
    kHttpServerPortFieldNumber = 3,
    kMetricRatioFieldNumber = 4,
    kMetricIntervalSecFieldNumber = 5,
    kDiscardRatioFieldNumber = 6,
    kThreadPoolSizeFieldNumber = 7,
  };
  // string server_addr = 1;
  void clear_server_addr() ;
  const std::string& server_addr() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_server_addr(Arg_&& arg, Args_... args);
  std::string* mutable_server_addr();
  PROTOBUF_NODISCARD std::string* release_server_addr();
  void set_allocated_server_addr(std::string* value);

  private:
  const std::string& _internal_server_addr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_server_addr(
      const std::string& value);
  std::string* _internal_mutable_server_addr();

  public:
  // uint32 grpc_server_port = 2;
  void clear_grpc_server_port() ;
  ::uint32_t grpc_server_port() const;
  void set_grpc_server_port(::uint32_t value);

  private:
  ::uint32_t _internal_grpc_server_port() const;
  void _internal_set_grpc_server_port(::uint32_t value);

  public:
  // uint32 http_server_port = 3;
  void clear_http_server_port() ;
  ::uint32_t http_server_port() const;
  void set_http_server_port(::uint32_t value);

  private:
  ::uint32_t _internal_http_server_port() const;
  void _internal_set_http_server_port(::uint32_t value);

  public:
  // uint32 metric_ratio = 4;
  void clear_metric_ratio() ;
  ::uint32_t metric_ratio() const;
  void set_metric_ratio(::uint32_t value);

  private:
  ::uint32_t _internal_metric_ratio() const;
  void _internal_set_metric_ratio(::uint32_t value);

  public:
  // uint32 metric_interval_sec = 5;
  void clear_metric_interval_sec() ;
  ::uint32_t metric_interval_sec() const;
  void set_metric_interval_sec(::uint32_t value);

  private:
  ::uint32_t _internal_metric_interval_sec() const;
  void _internal_set_metric_interval_sec(::uint32_t value);

  public:
  // uint32 discard_ratio = 6;
  void clear_discard_ratio() ;
  ::uint32_t discard_ratio() const;
  void set_discard_ratio(::uint32_t value);

  private:
  ::uint32_t _internal_discard_ratio() const;
  void _internal_set_discard_ratio(::uint32_t value);

  public:
  // uint32 thread_pool_size = 7;
  void clear_thread_pool_size() ;
  ::uint32_t thread_pool_size() const;
  void set_thread_pool_size(::uint32_t value);

  private:
  ::uint32_t _internal_thread_pool_size() const;
  void _internal_set_thread_pool_size(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:bazel_template.proto.BaseConfig)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 7, 0,
      51, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_BaseConfig_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BaseConfig& from_msg);
    ::google::protobuf::internal::ArenaStringPtr server_addr_;
    ::uint32_t grpc_server_port_;
    ::uint32_t http_server_port_;
    ::uint32_t metric_ratio_;
    ::uint32_t metric_interval_sec_;
    ::uint32_t discard_ratio_;
    ::uint32_t thread_pool_size_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_config_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BaseConfig

// string server_addr = 1;
inline void BaseConfig::clear_server_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_addr_.ClearToEmpty();
}
inline const std::string& BaseConfig::server_addr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:bazel_template.proto.BaseConfig.server_addr)
  return _internal_server_addr();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BaseConfig::set_server_addr(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_addr_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:bazel_template.proto.BaseConfig.server_addr)
}
inline std::string* BaseConfig::mutable_server_addr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_server_addr();
  // @@protoc_insertion_point(field_mutable:bazel_template.proto.BaseConfig.server_addr)
  return _s;
}
inline const std::string& BaseConfig::_internal_server_addr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.server_addr_.Get();
}
inline void BaseConfig::_internal_set_server_addr(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_addr_.Set(value, GetArena());
}
inline std::string* BaseConfig::_internal_mutable_server_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.server_addr_.Mutable( GetArena());
}
inline std::string* BaseConfig::release_server_addr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:bazel_template.proto.BaseConfig.server_addr)
  return _impl_.server_addr_.Release();
}
inline void BaseConfig::set_allocated_server_addr(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.server_addr_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.server_addr_.IsDefault()) {
          _impl_.server_addr_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bazel_template.proto.BaseConfig.server_addr)
}

// uint32 grpc_server_port = 2;
inline void BaseConfig::clear_grpc_server_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grpc_server_port_ = 0u;
}
inline ::uint32_t BaseConfig::grpc_server_port() const {
  // @@protoc_insertion_point(field_get:bazel_template.proto.BaseConfig.grpc_server_port)
  return _internal_grpc_server_port();
}
inline void BaseConfig::set_grpc_server_port(::uint32_t value) {
  _internal_set_grpc_server_port(value);
  // @@protoc_insertion_point(field_set:bazel_template.proto.BaseConfig.grpc_server_port)
}
inline ::uint32_t BaseConfig::_internal_grpc_server_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.grpc_server_port_;
}
inline void BaseConfig::_internal_set_grpc_server_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.grpc_server_port_ = value;
}

// uint32 http_server_port = 3;
inline void BaseConfig::clear_http_server_port() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.http_server_port_ = 0u;
}
inline ::uint32_t BaseConfig::http_server_port() const {
  // @@protoc_insertion_point(field_get:bazel_template.proto.BaseConfig.http_server_port)
  return _internal_http_server_port();
}
inline void BaseConfig::set_http_server_port(::uint32_t value) {
  _internal_set_http_server_port(value);
  // @@protoc_insertion_point(field_set:bazel_template.proto.BaseConfig.http_server_port)
}
inline ::uint32_t BaseConfig::_internal_http_server_port() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.http_server_port_;
}
inline void BaseConfig::_internal_set_http_server_port(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.http_server_port_ = value;
}

// uint32 metric_ratio = 4;
inline void BaseConfig::clear_metric_ratio() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.metric_ratio_ = 0u;
}
inline ::uint32_t BaseConfig::metric_ratio() const {
  // @@protoc_insertion_point(field_get:bazel_template.proto.BaseConfig.metric_ratio)
  return _internal_metric_ratio();
}
inline void BaseConfig::set_metric_ratio(::uint32_t value) {
  _internal_set_metric_ratio(value);
  // @@protoc_insertion_point(field_set:bazel_template.proto.BaseConfig.metric_ratio)
}
inline ::uint32_t BaseConfig::_internal_metric_ratio() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.metric_ratio_;
}
inline void BaseConfig::_internal_set_metric_ratio(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.metric_ratio_ = value;
}

// uint32 metric_interval_sec = 5;
inline void BaseConfig::clear_metric_interval_sec() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.metric_interval_sec_ = 0u;
}
inline ::uint32_t BaseConfig::metric_interval_sec() const {
  // @@protoc_insertion_point(field_get:bazel_template.proto.BaseConfig.metric_interval_sec)
  return _internal_metric_interval_sec();
}
inline void BaseConfig::set_metric_interval_sec(::uint32_t value) {
  _internal_set_metric_interval_sec(value);
  // @@protoc_insertion_point(field_set:bazel_template.proto.BaseConfig.metric_interval_sec)
}
inline ::uint32_t BaseConfig::_internal_metric_interval_sec() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.metric_interval_sec_;
}
inline void BaseConfig::_internal_set_metric_interval_sec(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.metric_interval_sec_ = value;
}

// uint32 discard_ratio = 6;
inline void BaseConfig::clear_discard_ratio() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.discard_ratio_ = 0u;
}
inline ::uint32_t BaseConfig::discard_ratio() const {
  // @@protoc_insertion_point(field_get:bazel_template.proto.BaseConfig.discard_ratio)
  return _internal_discard_ratio();
}
inline void BaseConfig::set_discard_ratio(::uint32_t value) {
  _internal_set_discard_ratio(value);
  // @@protoc_insertion_point(field_set:bazel_template.proto.BaseConfig.discard_ratio)
}
inline ::uint32_t BaseConfig::_internal_discard_ratio() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.discard_ratio_;
}
inline void BaseConfig::_internal_set_discard_ratio(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.discard_ratio_ = value;
}

// uint32 thread_pool_size = 7;
inline void BaseConfig::clear_thread_pool_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.thread_pool_size_ = 0u;
}
inline ::uint32_t BaseConfig::thread_pool_size() const {
  // @@protoc_insertion_point(field_get:bazel_template.proto.BaseConfig.thread_pool_size)
  return _internal_thread_pool_size();
}
inline void BaseConfig::set_thread_pool_size(::uint32_t value) {
  _internal_set_thread_pool_size(value);
  // @@protoc_insertion_point(field_set:bazel_template.proto.BaseConfig.thread_pool_size)
}
inline ::uint32_t BaseConfig::_internal_thread_pool_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.thread_pool_size_;
}
inline void BaseConfig::_internal_set_thread_pool_size(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.thread_pool_size_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace bazel_template


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_config_2eproto_2epb_2eh
