// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: config.proto
// Protobuf C++ Version: 5.27.2

#include "config.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace bazel_template {
namespace proto {

inline constexpr BaseConfig::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : server_addr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        grpc_server_port_{0u},
        http_server_port_{0u},
        metric_ratio_{0u},
        metric_interval_sec_{0u},
        discard_ratio_{0u},
        thread_pool_size_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BaseConfig::BaseConfig(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BaseConfigDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BaseConfigDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BaseConfigDefaultTypeInternal() {}
  union {
    BaseConfig _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BaseConfigDefaultTypeInternal _BaseConfig_default_instance_;
}  // namespace proto
}  // namespace bazel_template
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_config_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_config_2eproto = nullptr;
const ::uint32_t
    TableStruct_config_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _impl_.server_addr_),
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _impl_.grpc_server_port_),
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _impl_.http_server_port_),
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _impl_.metric_ratio_),
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _impl_.metric_interval_sec_),
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _impl_.discard_ratio_),
        PROTOBUF_FIELD_OFFSET(::bazel_template::proto::BaseConfig, _impl_.thread_pool_size_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::bazel_template::proto::BaseConfig)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::bazel_template::proto::_BaseConfig_default_instance_._instance,
};
const char descriptor_table_protodef_config_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014config.proto\022\024bazel_template.proto\"\271\001\n"
    "\nBaseConfig\022\023\n\013server_addr\030\001 \001(\t\022\030\n\020grpc"
    "_server_port\030\002 \001(\r\022\030\n\020http_server_port\030\003"
    " \001(\r\022\024\n\014metric_ratio\030\004 \001(\r\022\033\n\023metric_int"
    "erval_sec\030\005 \001(\r\022\025\n\rdiscard_ratio\030\006 \001(\r\022\030"
    "\n\020thread_pool_size\030\007 \001(\rb\006proto3"
};
static ::absl::once_flag descriptor_table_config_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_config_2eproto = {
    false,
    false,
    232,
    descriptor_table_protodef_config_2eproto,
    "config.proto",
    &descriptor_table_config_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_config_2eproto::offsets,
    file_level_enum_descriptors_config_2eproto,
    file_level_service_descriptors_config_2eproto,
};
namespace bazel_template {
namespace proto {
// ===================================================================

class BaseConfig::_Internal {
 public:
};

BaseConfig::BaseConfig(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bazel_template.proto.BaseConfig)
}
inline PROTOBUF_NDEBUG_INLINE BaseConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::bazel_template::proto::BaseConfig& from_msg)
      : server_addr_(arena, from.server_addr_),
        _cached_size_{0} {}

BaseConfig::BaseConfig(
    ::google::protobuf::Arena* arena,
    const BaseConfig& from)
    : ::google::protobuf::Message(arena) {
  BaseConfig* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, grpc_server_port_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, grpc_server_port_),
           offsetof(Impl_, thread_pool_size_) -
               offsetof(Impl_, grpc_server_port_) +
               sizeof(Impl_::thread_pool_size_));

  // @@protoc_insertion_point(copy_constructor:bazel_template.proto.BaseConfig)
}
inline PROTOBUF_NDEBUG_INLINE BaseConfig::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : server_addr_(arena),
        _cached_size_{0} {}

inline void BaseConfig::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, grpc_server_port_),
           0,
           offsetof(Impl_, thread_pool_size_) -
               offsetof(Impl_, grpc_server_port_) +
               sizeof(Impl_::thread_pool_size_));
}
BaseConfig::~BaseConfig() {
  // @@protoc_insertion_point(destructor:bazel_template.proto.BaseConfig)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BaseConfig::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.server_addr_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
BaseConfig::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_._cached_size_),
              false,
          },
          &BaseConfig::MergeImpl,
          &BaseConfig::kDescriptorMethods,
          &descriptor_table_config_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 51, 2> BaseConfig::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_BaseConfig_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bazel_template::proto::BaseConfig>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string server_addr = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.server_addr_)}},
    // uint32 grpc_server_port = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BaseConfig, _impl_.grpc_server_port_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.grpc_server_port_)}},
    // uint32 http_server_port = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BaseConfig, _impl_.http_server_port_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.http_server_port_)}},
    // uint32 metric_ratio = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BaseConfig, _impl_.metric_ratio_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.metric_ratio_)}},
    // uint32 metric_interval_sec = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BaseConfig, _impl_.metric_interval_sec_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.metric_interval_sec_)}},
    // uint32 discard_ratio = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BaseConfig, _impl_.discard_ratio_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.discard_ratio_)}},
    // uint32 thread_pool_size = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BaseConfig, _impl_.thread_pool_size_), 63>(),
     {56, 63, 0, PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.thread_pool_size_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string server_addr = 1;
    {PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.server_addr_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 grpc_server_port = 2;
    {PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.grpc_server_port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 http_server_port = 3;
    {PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.http_server_port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 metric_ratio = 4;
    {PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.metric_ratio_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 metric_interval_sec = 5;
    {PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.metric_interval_sec_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 discard_ratio = 6;
    {PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.discard_ratio_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 thread_pool_size = 7;
    {PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.thread_pool_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
    "\37\13\0\0\0\0\0\0"
    "bazel_template.proto.BaseConfig"
    "server_addr"
  }},
};

PROTOBUF_NOINLINE void BaseConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:bazel_template.proto.BaseConfig)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.server_addr_.ClearToEmpty();
  ::memset(&_impl_.grpc_server_port_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.thread_pool_size_) -
      reinterpret_cast<char*>(&_impl_.grpc_server_port_)) + sizeof(_impl_.thread_pool_size_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* BaseConfig::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:bazel_template.proto.BaseConfig)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string server_addr = 1;
  if (!this->_internal_server_addr().empty()) {
    const std::string& _s = this->_internal_server_addr();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bazel_template.proto.BaseConfig.server_addr");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // uint32 grpc_server_port = 2;
  if (this->_internal_grpc_server_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_grpc_server_port(), target);
  }

  // uint32 http_server_port = 3;
  if (this->_internal_http_server_port() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_http_server_port(), target);
  }

  // uint32 metric_ratio = 4;
  if (this->_internal_metric_ratio() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_metric_ratio(), target);
  }

  // uint32 metric_interval_sec = 5;
  if (this->_internal_metric_interval_sec() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        5, this->_internal_metric_interval_sec(), target);
  }

  // uint32 discard_ratio = 6;
  if (this->_internal_discard_ratio() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        6, this->_internal_discard_ratio(), target);
  }

  // uint32 thread_pool_size = 7;
  if (this->_internal_thread_pool_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this->_internal_thread_pool_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bazel_template.proto.BaseConfig)
  return target;
}

::size_t BaseConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bazel_template.proto.BaseConfig)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string server_addr = 1;
  if (!this->_internal_server_addr().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_server_addr());
  }

  // uint32 grpc_server_port = 2;
  if (this->_internal_grpc_server_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_grpc_server_port());
  }

  // uint32 http_server_port = 3;
  if (this->_internal_http_server_port() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_http_server_port());
  }

  // uint32 metric_ratio = 4;
  if (this->_internal_metric_ratio() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_metric_ratio());
  }

  // uint32 metric_interval_sec = 5;
  if (this->_internal_metric_interval_sec() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_metric_interval_sec());
  }

  // uint32 discard_ratio = 6;
  if (this->_internal_discard_ratio() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_discard_ratio());
  }

  // uint32 thread_pool_size = 7;
  if (this->_internal_thread_pool_size() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_thread_pool_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void BaseConfig::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BaseConfig*>(&to_msg);
  auto& from = static_cast<const BaseConfig&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:bazel_template.proto.BaseConfig)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_server_addr().empty()) {
    _this->_internal_set_server_addr(from._internal_server_addr());
  }
  if (from._internal_grpc_server_port() != 0) {
    _this->_impl_.grpc_server_port_ = from._impl_.grpc_server_port_;
  }
  if (from._internal_http_server_port() != 0) {
    _this->_impl_.http_server_port_ = from._impl_.http_server_port_;
  }
  if (from._internal_metric_ratio() != 0) {
    _this->_impl_.metric_ratio_ = from._impl_.metric_ratio_;
  }
  if (from._internal_metric_interval_sec() != 0) {
    _this->_impl_.metric_interval_sec_ = from._impl_.metric_interval_sec_;
  }
  if (from._internal_discard_ratio() != 0) {
    _this->_impl_.discard_ratio_ = from._impl_.discard_ratio_;
  }
  if (from._internal_thread_pool_size() != 0) {
    _this->_impl_.thread_pool_size_ = from._impl_.thread_pool_size_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BaseConfig::CopyFrom(const BaseConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bazel_template.proto.BaseConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BaseConfig::InternalSwap(BaseConfig* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.server_addr_, &other->_impl_.server_addr_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.thread_pool_size_)
      + sizeof(BaseConfig::_impl_.thread_pool_size_)
      - PROTOBUF_FIELD_OFFSET(BaseConfig, _impl_.grpc_server_port_)>(
          reinterpret_cast<char*>(&_impl_.grpc_server_port_),
          reinterpret_cast<char*>(&other->_impl_.grpc_server_port_));
}

::google::protobuf::Metadata BaseConfig::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace bazel_template
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_config_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
